language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: "pip install -r requirements.txt"
script: sh ./test.sh

deploy:
  provider: pypi
  user: utgwkk
  password:
    secure: "cUs8dyVUjbkfr42iuIFnuxxFpQdoCyX+f0xVJrUkkiNQ3t/7q6yzbnZiXrxPySTcrUeTfWefan3/maQZCaotj+jchjUDnRNYPzbiQmmh0qdkQID/k4cKYcvUP6zDTWAha4vQGSvyoAvXksYC0tbmgMPvI3g5cxwG8si3hs+Kz5bVwq3eJM8qT4I11T/D/HYHBPGT0nPav79oUjZgXjCMIx7F++kB74ZXJ7NI4cd8CbqloEZ2FHVPwsSt7YECOaPnfFUuZ818Yanuoz0oc7v18s8/4jtFmuS5dvgnQnaa4HXrh5z997WQiZwTF1ax//uUf/ePEZ6QVBHiK3Vrcpuk4CmdUDnyAUQs7VlIubWnzSIJP8vNWWccK/PwLNM6s8EOXYWfguYWETzgq2ey3p1WnuL8NHN14QBhQDfFq3ylrjsbSMtz+meZkb1Y+ZAIQAD+grauGfdc4BULohTvujShjjjn0FIWOftL9kyDYFrNUuEXRfl34baDvXcaLbNDC3IU31CA1UGL0IAIVR3zpjic/bL4zq98gTNgbN101VCbFpGcDv0epz8HKwFbTPWl/3rPd3H8AfiwxcOZMZ5gVYdXfcXB8Z+7P6QOl+gaOzr57WfR4eoxNWh6L4cAIDziSCC1tZ/qCjfwhk8BPG5ldKZcxETx4lKz4k9YZWmOO95bzI0="
  on:
    tags: true
