language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: "pip install -r requirements.txt"
script: sh ./test.sh

deploy:
  provider: pypi
  user: utgwkk
  password:
    secure: "qJe//5nxU54/qvQPjA/MCteILWniMrAXFPhUUTR6vAT5Yq3VAGIMbuJ+NJVZEavyE2wnjgWzs+khGdnslusJVYl28EMsJwQSDvWHCEXENzgZMkE13X20PMlcc5pdyaQDrJXp6c6zXsD9Mcf2RpJbTnlzx6gEoaoL9gDkeBDsuaiOeIyB+8mY+Atmxdu25yoHIIIW/dZpFfpd+MTA01+N/BW7mMh2JY5TnyUp72VViTYnZSxvh+c/DspF7/eXybuIAqkoVWx/BKAp5+akBmQVygK0SytBjXUFL12BM9fK5QKnt54pnXU1lVK1Y+KA0cD9/vsQW8cThs8m6zTjOufi3D/61Ulox3/SBTmiUA36CkKr5IdEEcPM1X3DC35JDYeGRb5v9+pNZ/hnZ/TQ5qFmJ5l/Cd/WZ+vtrBqxeupD1pNV0ocqY1t69Sq2iUuLcw+m4Xb4Go6cXGp0RBJGeEBRuzo6zGB7vk5N01T2KYCy8lJxnY+T818UlgnkBsPJiWLG5sjW5l/BWgL1l4ZPWFFj5kFS8RpeAD+nATNo0rWE8QTEOIDJ00kXBCeqb1eokrLAHgUjJ1hGmBjx8vTrXZymNI0BADkKHm/jDGHUgEQ9iZNelGsrDflXZB2MasVIyS31aHhhKlNkNY8w62koXuZxBTFAeOzD63ge5AdQhuwysZE="
  on:
    tags: true
